// <auto-generated/>
#nullable enable
namespace GeneratorFixture;

public static class SnapshotCommandsHostingExtensions
{
    public static global::Minamo.Hosting.MinamoHost AddSnapshotModule(this global::Minamo.Hosting.MinamoHost host)
    {
        return host.Module("snapshot", module =>
        {
            module.RawCommand("echo", "Echoes text.", "snapshot.read", context =>
            {
                var result = global::GeneratorFixture.SnapshotCommands.Echo(global::Minamo.Hosting.MinamoCommandConvert.ToString(context.ExecutionContext, context.RawArgument(0)), global::Minamo.Hosting.MinamoCommandConvert.ToInt32(context.ExecutionContext, context.RawArgument(1)));
                return global::Minamo.Hosting.MinamoCommandConvert.FromString(result);
            },
            global::Minamo.Hosting.MinamoCommandParameter.Required<string>("value"),
            global::Minamo.Hosting.MinamoCommandParameter.Optional<int>("count", 2));
            module.RawCommand("Maybe", null, null, context =>
            {
                var result = global::GeneratorFixture.SnapshotCommands.Maybe(context.RawArgument(0) is global::Minamo.Runtime.Types.MinamoNil ? default(int?) : global::Minamo.Hosting.MinamoCommandConvert.ToInt32(context.ExecutionContext, context.RawArgument(0)));
                return result.HasValue ? global::Minamo.Hosting.MinamoCommandConvert.FromInteger(result.Value) : global::Minamo.Runtime.Types.MinamoNil.Instance;
            },
            global::Minamo.Hosting.MinamoCommandParameter.Required<int?>("value"));
        });
    }
}
