<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(MinamoRuntimeTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Minamo.Examples.QuestConsole</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Minamo.Generators\Minamo.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\Minamo\Minamo.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Scripts\**\*.nami" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
