param(
    [switch]$Check
)

$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$recipesPath = Join-Path $repoRoot "Docs\Language\Recipes.md"
$recipes = @(
    [pscustomobject]@{
        File = "01-collections.nami"
        Title = "Collections and data transformation"
        Description = "Filters a collection and formats the resulting values. It demonstrates arrays, comprehensions, loops, and string formatting."
    },
    [pscustomobject]@{
        File = "02-patterns.nami"
        Title = "Pattern matching"
        Description = 'Classifies values with `match`, including literal, range, and fallback patterns.'
    },
    [pscustomobject]@{
        File = "03-types-and-traits.nami"
        Title = "Types and traits"
        Description = "Defines a value type and a trait implementation, then uses the resulting method from ordinary script code."
    },
    [pscustomobject]@{
        File = "04-iterators.nami"
        Title = "Iterators"
        Description = 'Declares an iterator function with `yield` and consumes it with `for`.'
    },
    [pscustomobject]@{
        File = "05-exceptions.nami"
        Title = "Exceptions"
        Description = "Throws and catches an application error while keeping the script running."
    }
    [pscustomobject]@{
        File = "06-modules.nami"
        Title = "Modules and visibility"
        Description = "Imports two local modules, uses an alias and a selected import, and keeps a pricing constant private to its module."
    }
    [pscustomobject]@{
        File = "07-enums-and-state.nami"
        Title = "Enums and state"
        Description = "Models delivery states with enum cases and turns each state into a user-facing message with match."
    }
    [pscustomobject]@{
        File = "08-functions-and-closures.nami"
        Title = "Functions and closures"
        Description = "Builds a stateful counter with a closure and passes a lambda as a transformation function."
    }
    [pscustomobject]@{
        File = "09-dictionaries-and-tuples.nami"
        Title = "Dictionaries and tuples"
        Description = "Converts a labeled tuple into a dictionary, updates a value, applies a fallback, and enumerates the entries."
    }
    [pscustomobject]@{
        File = "10-cleanup-and-errors.nami"
        Title = "Cleanup and errors"
        Description = "Recovers from an application error and uses finally to release work owned by the attempted operation."
    }
    [pscustomobject]@{
        File = "11-traits-as-interfaces.nami"
        Title = "Traits as interfaces"
        Description = "Uses a trait as a common billable interface, shares a default description, and accepts multiple concrete types through the trait contract."
    }
    [pscustomobject]@{
        File = "12-select-composition.nami"
        Title = "Select composition"
        Description = "Adds a state-less child select's choices to a parent state and declares host-facing descriptions for both selects."
        Arguments = "--do setup"
    }
)

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("<!-- Generated by scripts/generate-recipes.ps1. Do not edit directly. -->")
$lines.Add("")
$lines.Add("# Minamo recipes")
$lines.Add("")
$lines.Add("This page contains small, complete programs that run with the Minamo console. For a language tour, see the [overview](Overview.md); for syntax details, see the [grammar reference](../Reference/Grammar.md).")
$lines.Add("")
$lines.Add("Build the Release console once from the repository root:")
$lines.Add("")
$lines.Add('```powershell')
$lines.Add(".\scripts\build-local.ps1 -Configuration Release")
$lines.Add('```')

foreach ($recipe in $recipes)
{
    $sourcePath = Join-Path (Join-Path $repoRoot "Examples\Language") $recipe.File
    $source = (Get-Content -Raw -Encoding UTF8 $sourcePath).TrimEnd()

    $lines.Add("")
    $lines.Add("## " + $recipe.Title)
    $lines.Add("")
    $lines.Add($recipe.Description)
    $lines.Add("")
    $lines.Add('```swift')
    $lines.Add($source)
    $lines.Add('```')
    $lines.Add("")
    $lines.Add("Run it with:")
    $lines.Add("")
    $lines.Add('```powershell')
    $arguments = if ($recipe.PSObject.Properties.Name -contains "Arguments")
    {
        " " + $recipe.Arguments
    }
    else
    {
        ""
    }
    $lines.Add((".\bin\minamo.exe .\Examples\Language\{0} -nologo{1}" -f $recipe.File, $arguments))
    $lines.Add('```')
    $lines.Add("")
    $lines.Add("Source: [" + $recipe.File + "](../../Examples/Language/" + $recipe.File + ")")
}

$lines.Add("")
$lines.Add('The Release smoke test executes every listed recipe. Run `scripts/generate-recipes.ps1 -Check` to verify that this page matches the source files.')
$expected = $lines -join [Environment]::NewLine

if ($Check)
{
    $actual = Get-Content -Raw -Encoding UTF8 $recipesPath
    if ($actual.TrimEnd() -ne $expected.TrimEnd())
    {
        throw "Docs/Language/Recipes.md is out of date. Run scripts/generate-recipes.ps1."
    }

    return
}

$expected | Set-Content -Encoding UTF8 $recipesPath
